trigger:
- dev

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET SDK'
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
- checkout: self
  fetchDepth: 0
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'magellantgpt'
    scannerMode: 'MSBuild'
    projectKey: '2024-DI3-P3-G3_API'
    projectName: 'API'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: 'Exécuter les tests unitaires'
#   inputs:
#     command: test
#     projects: '**/*API.xUnitTest.csproj'
#     arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- task: SonarCloudAnalyze@1
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'API_$(Build.BuildNumber)'
  condition: succeededOrFailed()

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'DI3P3-A1 (2dc6f934-dac5-480d-8f38-76edbb3baa80)'
    appType: 'webApp'
    WebAppName: 'apiappmagellangptg3dev'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'